Repository diynyk/Exchange-Rates, pull requests merged in 2021-03, with the labels that each got.

#1 done
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile
  README.md
  composer.json
  composer.lock
  config.yml
  env/docker-compose.yml
  env/php/dockerfile
  fixer
  php-cli/Dockerfile
  php_web.sh
  prun.sh
  src/BitrixApiWrapper.php
  src/Bootstrap.php
  src/Commands/FixCommand.php
  src/Commands/SetRateCommand.php
  src/Currency.php
  src/EntityAbstract.php
  src/EntityEnumerator.php
  src/EntityFixer.php
  src/ZaprosNBU.php
  www/composer
  www/src/PostNBU.php
Labels: enhancement

#3 fix build
  Dockerfile
  README.md
  php_web.sh
Labels: bug

#2 export from postman
  postman/exchenge rate.postman_collection.json
Labels: documentation
